
--11.10

SELECT *, REPLICATE ('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO) FROM TEST 

UPDATE TEST SET SIRANO2=REPLICATE ('0',8-LEN(SIRANO))+CONVERT(VARCHAR,SIRANO) FROM TEST 

--CONVERTLEYÝNCE TEK SIFIRLAR DEÐÝL SAYIDA GELDÝ YANNA

--11.11 replace

SELECT 'YAÐMUR ÞÝMÞEK'
SELECT REPLACE('YAÐMUR ÞÝMÞEK','ÞÝMÞEK','TUNÇAY')