--ÖDEME TÜRÜNE GÖRE DAÐILIM HANGÝ AY NE KADAR OLARAK
--SELECT DISTINCT PAYMENTTYPE FROM PAYMENTS 
-- KAÇ TANE ÖDEME ÞEKLÝ OLD. BAKTIK.
--JOINE GEREK YOK BÝLGÝLER ZATEN PAYMENTSTE
SELECT 
DATEPART(YEAR,DATE_) AS YIL,
DATEPART(MONTH,DATE_) AS AY,
--PAYMENTTYPE AS ODEMETURU,
CASE
WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
END AS ODEMETURU_ACIKLAMA,

SUM(PAYMENTTOTAL) AS TOPLAMTUTAR

FROM PAYMENTS

GROUP BY DATEPART(YEAR,DATE_), DATEPART(MONTH,DATE_),PAYMENTTYPE
ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)