-- TARÝHE GÖRE SÝPARÝÞ DAÐILIMINI GETÝREN SORGU

SELECT
--TOP 10 
	CONVERT(DATE,O.DATE_) AS TARIH,
	SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
	SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
	COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI

FROM ORDERS O 

	JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON O.ADDRESSID=A.ID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID 

GROUP BY CONVERT(DATE,O.DATE_)
ORDER BY CONVERT(DATE,O.DATE_) --TARIHE GÖRE SIRALADIK