--AYLARA GÖRE

SELECT
--TOP 10 
	    DATEPART(YEAR,O.DATE_) AS YIL,
		DATEPART(MONTH,O.DATE_) AS AY,
		CASE
		WHEN DATEPART(MONTH,O.DATE_)=1  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=2  THEN 'ÞUBAT'
		WHEN DATEPART(MONTH,O.DATE_)=3  THEN 'MART'
		WHEN DATEPART(MONTH,O.DATE_)=4  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=5  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=6  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=7  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=8  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=9  THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'OCAK'
		WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'OCAK'
		END AS AYADI,

		SUM(OD.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
		SUM(OD.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
		COUNT(OD.ID) AS TOPLAMSIPARIS_SAYISI

FROM ORDERS O 

	JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON O.ADDRESSID=A.ID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS IT ON IT.ID=OD.ITEMID 

GROUP BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
ORDER BY DATEPART(YEAR,O.DATE_),DATEPART(MONTH,O.DATE_)