SELECT
U.NAMESURNAME,
U.GENDER,
U.BIRTHDATE,
C.COUNTRY, 
CT.CITY,
T.TOWN,
D.DISTRICT,
A. ADRESSTEXT
FROM 
USERS U,ADRESS A,COUNTRIES C, CITIES CT
,TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID
AND CT.ID=A.CITYID AND T.ID=A.TOWNID 
AND D.ID=A.DISTRITID
AND CT.CITY='NÝÐDE'
--AND U.ID=4
ORDER BY U.NAMESURNAME

