CREATE DATABASE HASTALAR
USE HASTALAR

CREATE TABLE HASTA 
(HASTA_ID INT PRIMARY KEY IDENTITY (1,1),
AD VARCHAR(25),
SOYAD VARCHAR(35),
DOGUMTARIHI DATE,
CONSTRAINT YASKISITLA CHECK (DATEDIFF(YEAR,DOGUMTARIHI,GetDate())>18 and DATEDIFF(YEAR,DOGUMTARIHI,GetDate())<75)
)
INSERT INTO HASTA (AD ,SOYAD , DOGUMTARIHI)
VALUES
('DOÐUKAN' , 'TUNÇAY' ,'2003-10-05'),
('ARDA ENES','ÞÝMÞEK','2002-02-19'),
('YAÐMUR ','ÞÝMÞEK','2003-02-07');


INSERT INTO HASTA (AD ,SOYAD , DOGUMTARIHI)
VALUES 
('AYÞENUR','ÞÝMÞEK','2001-09-20');


SELECT * FROM HASTA 

TRUNCATE TABLE HASTA

DBCC CHECKIDENT('HASTA', RESEED, 2);


---

CREATE TABLE Customer (CustId INTEGER PRIMARY KEY, CLstNm NCHAR VARYING (50))
CREATE TABLE Orders1 (OrderId INTEGER PRIMARY KEY, CustId INTEGER , OrderNotes NCHAR VARYING (255),
CONSTRAINT ASD FOREIGN KEY (CustId) REFERENCES Customer ON UPDATE CASCADE ON DELETE CASCADE)

ALTER TABLE Orders 
ADD FOREIGN KEY (CustId) REFERENCES Customers  (CustId)
ON DELETE CASCADE;

--alter table ile eklersek add olur çünkü sonradan ekleme
--fakat direkt create ile oluþturursak create içinde belirtirsek
--böyle uðraþmayýz


-- 1.durumu kullanmak içn 2. durumdan foreýgn keyi kaldýrýcam silemedik...
--:(

--isim yaðmur girilmesin bir isimler tablosu oluþtur kýsýtla bunu 
CREATE DATABASE CUSTOMERNAME
USE CUSTOMERNAME

CREATE TABLE NAMES
(NameId INT IDENTITY(1,1),NAMES VARCHAR(50),SURNAME VARCHAR(100),LýckName VARCHAR(100))

ALTER TABLE NAMES
ADD CONSTRAINT NAMES1 CHECK (NAMES<>'Yaðmur')

INSERT INTO  NAMES (NAMES,SURNAME,LýckName)
VALUES ('Yaðmur','Þimþek','ÞÝMÞÝR')


INSERT INTO  NAMES (NAMES,SURNAME,LýckName)
VALUES ('doðukan','Þimþek','ÞÝMÞÝR')

select * from NAMES
DBCC CHECKIDENT('NAMES', RESEED, 0);

TRUNCATE TABLE NAMES

