SELECT 
CT.CITY,COUNT(U.ID) AS KULLANICISAYIISI
FROM 
USERS U,ADRESS A,COUNTRIES C, CITIES CT,TOWNS T,DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID AND T.ID=A.TOWNID 
AND D.ID=A.DISTRITID

GROUP BY CT.CITY