SELECT CITY, SUM(TOTALPRICE) AS TOTALPRICE
,COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERCOUNT

FROM SALES
--WHERE CITY IN ('ANKARA ','ÝSTANBUL','ÝZMÝR','AYDIN','HATAY')
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000
AND COUNT(DISTINCT CUSTOMERNAME)>500
ORDER BY SUM(TOTALPRICE) DESC