--ORTALAMA TESLÝMAT SÜRSÝ

SELECT
    U.ID ,U.NAMESURNAME,
	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMATESLIMAT_SAAT,
	SUM(O.TOTALPRICE) AS TOPLAM_SIAPRIS_TUTARI,
	COUNT(O.ID) AS SIPARISSAYISI
FROM ORDERS O 

	JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON O.ADDRESSID=A.ID
	INNER JOIN CITIES CT ON CT.ID=A.CITYID
	INNER JOIN TOWNS T ON T.ID=A.TOWNID
	INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	INNER JOIN INVOICES I ON I.ORDERID=O.ID

--HAVING MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_))>AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))

GROUP BY  
U.ID ,U.NAMESURNAME
HAVING AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) > 22
ORDER BY 4 DESC