CREATE TABLE WRÝTERS (
WRITER_ID INT IDENTITY (1,1) PRIMARY KEY ,
WRÝTER_NAME VARCHAR(100),
WRÝTER_SURNAME VARCHAR(100)
);
CREATE TABLE YAYINEVLERÝ(
YAYINEVÝ_ID INT IDENTITY (1,1) PRIMARY KEY ,
YAYINEVÝ_NAME VARCHAR(100),
ADRES VARCHAR(200)
);
CREATE TABLE KÝTAPLAR (
KÝTAP_ID INT IDENTITY (1,1) PRIMARY KEY ,
WRITERS_ID INT ,
YAYINEVÝ_ID INT ,
YAYINEVÝ_DATE DATE 
);
-- OLUÞTURDUK ÞÝMDÝ BUNLARI DOLDURALIM.

INSERT INTO
WRÝTERS (WRÝTER_NAME, WRÝTER_SURNAME)
VALUES ('Yaðmur','ÞÝMÞEK'),
('Doðukan','TUNÇAY'),
('Ayþe','SÖNMEZ')

DBCC CHECKIDENT ('WRÝTERS', RESEED,0)

INSERT INTO
YAYINEVLERÝ (YAYINEVÝ_NAME, ADRES)
VALUES ('XYZ YAYINEVÝ','ÝSTANBUL'),
('ABC YAYINEVÝ','ANKARA'),
('DEF','BANDIRMA')

INSERT INTO
KÝTAPLAR (WRITERS_ID, YAYINEVÝ_ID,YAYINEVÝ_DATE,baþlik,StokMiktari)
VALUES (1,1,'2023-02-07','yaðmur dodoyu seviyo',100),
(2,2,'2003-02-05','doðukan yaðmuru seviyo',200)

DBCC CHECKIDENT ('KÝTAPLAR', RESEED,0)

-- DOLDURDUK ÞÝMDÝ ÇAÐIRALIM
SELECT w.WRÝTER_NAME,w.WRÝTER_SURNAME , k.baþlik as KÝTAP_ADÝ, K.YAYINEVÝ_DATE AS YAYINLANMA_TARÝHÝ ,y.YAYINEVÝ_NAME ,k.StokMiktari

FROM KÝTAPLAR k 

JOIN WRÝTERS w ON W.WRITER_ID=K.WRITERS_ID
JOIN YAYINEVLERÝ y ON Y.YAYINEVÝ_ID=k.YAYINEVÝ_ID
-- stoklarý yenileyelim
UPDATE KÝTAPLAR SET StokMiktari=200 WHERE baþlik='yaðmur dodoyu seviyo' --100dü 200 yaptýk stoklarý

--yazar bazýnda kitap sayýlarý

SELECT w.WRÝTER_NAME AS YazarAdi , w.WRÝTER_SURNAME AS YazarSoyadi,COUNT(k.Kitap_ID) AS KitapSayisi 
FROM WRÝTERS w
LEFT JOIN KÝTAPLAR k ON w.WRITER_ID=k.WRITERS_ID
GROUP BY w.WRÝTER_NAME ,w.WRÝTER_SURNAME
 --bu kiþiye ait kitap ýdlerin sayýsý


 --yeni bir projemiz fonksyion oluþturalým
CREATE OR ALTER FUNCTION dbo.EnYeniKitaplar ()
RETURNS @Result TABLE (KÝTAP_ID INT ,BAÞLÝK VARCHAR(200),WRÝTER_NAME VARCHAR (100),YAYINEVÝ_DATE DATE,YAYINEVÝ_NAME VARCHAR (100))
AS 
BEGIN 
	INSERT INTO @Result(KÝTAP_ID,BAÞLÝK, WRÝTER_NAME,YAYINEVÝ_DATE,YAYINEVÝ_NAME)

	SELECT TOP 5 k.KÝTAP_ID ,k.BAÞLÝK AS KÝTAPADÝ ,w.WRÝTER_NAME  AS YAZARADÝ,k.YAYINEVÝ_DATE,y.YAYINEVÝ_NAME
	FROM KÝTAPLAR k 
	JOIN WRÝTERS w ON k.WRITERS_ID=w.WRITER_ID
	JOIN YAYINEVLERÝ y ON k.YAYINEVÝ_ID=y.YAYINEVÝ_ID
	ORDER BY k.YAYINEVÝ_DATE DESC;
	RETURN  ;
END;
SELECT * FROM dbo.EnYeniKitaplar ();

--YAYINEVÝ BAZINDA STOK MÝKTARI 

CREATE OR ALTER FUNCTION dbo.YayinEviStok()
RETURNS @RESULT TABLE (YAYINEVÝ_NAME VARCHAR(100) , StokMiktari int)

AS
BEGIN 

INSERT INTO @RESULT (YAYINEVÝ_NAME,StokMiktari)

SELECT yay.YAYINEVÝ_NAME AS YayinEviAdi,SUM(k.StokMiktari) AS KitaplarinStokMiktarlari

FROM YAYINEVLERÝ yay 

JOIN KÝTAPLAR k ON yay.YAYINEVÝ_ID=k.YAYINEVÝ_ID

GROUP BY yay.YAYINEVÝ_NAME ORDER BY SUM(k.StokMiktari);

RETURN; 
END;

SELECT * FROM dbo.YayinEviStok();


--BÝZ BU PROJEDE YAZAR YAYINEVÝ  BÝLGÝLERÝNÝ KULLANRAK FONKSÝYONLAR OLUÞTURDUK. CREATE TABLE ÝLE TABLO OLUÞTURULDUÐUNU INSERT INTO VALUES ÝLE
--DOLDURULDUÐUNU ÖÐRENDÝK. FONKSÝYON OLUÞTURMAYI ÖÐRENDÝK. SELECT TOP ÝLE KAÇ TANE ÇAÐIRMAK ÝSTÝYORSAK O KADARINI ÇAÐIRABÝLÝCEÐÝMÝZÝ ÖÐRENDÝK.
--UPDATE ÝLE YENÝLEME YAPABÝLECEÐÝMÝZÝ ÖÐRENDÝK.
--DBCC CHECKIDENT ÝLE RESETLEME YAPABÝLÝRÝZ.