--SELECT * FROM SALES ORDER BY AMOUNT
--SELECT MIN(AMOUNT) FROM SALES
--SELECT MAX(AMOUNT) FROM SALES
--SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT( *) FROM SALES
--SELECT MIN(AMOUNT) FROM SALES
--SELECT MAX(AMOUNT) FROM SALES

--SELECT SUM (AMOUNT)AS TOPLAM, AVG(AMOUNT)AS OTALAMA FROM SALES

--SELECT
--CITY ,
--MIN(TOTALPRICE) AS MINPRICE, MAX (TOTALPRICE)MAXPRICE,
--COUNT(FICHENO) AS ROWCOUNT_,SUM(TOTALPRICE) TOTALPRICE,
--AVG(TOTALPRICE)  AVGPRICE
--FROM SALES GROUP BY CITY
--ORDER BY CITY
--ORDER BY SUM(TOTALPRICE)
--ÝL BAZLI KAÇA SATMIÞIM EN AZ KAÇA GÝBÝ ÖZELLÝKLERÝ VERÝYOR.


--SELECT 
--CITY,   --ÝL BAZLI EN AZ KAÇA SATMIÞIM ONU GÖSTERÝR.
--MIN(TOTALPRICE) AS MINPRICE
--FROM SALES 

--GROUP BY CITY
--ORDER BY SUM(TOTALPRICE) 

SELECT TOP 10
CITY, SUM(TOTALPRICE) AS TOPLAM
FROM SALES

GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

