SELECT * FROM CUSTOMERS

WHERE CITY='ÝSTANBUL'

ORDER BY 3 ASC, CUSTOMERNAME ASC --ADAN BAÞLAYIP SIRALIYOR.
-- ÝLK OLARAK CITYÝ ADAN BASLAYP SIRALIYOR 
--SONRA CUSTOMERNAMEYÝ ADAN BAÞLAAYRAK SIRALYOR. DESC 
--KOYARSAK TAM TERSÝNE SIRALAR.ORDER BY YANINA KOLON NUMARASINI YAZARSAKDA AYNI ANLAMA GELÝR.
--ÝLK ÖNCE BAÞA YAZILANA GÖRE SIRALAR.

