SELECT 
U.NAMESURNAME,COUNT(A.ID) AS ADRESSAYISI
FROM
USERS U,ADRESS A,COUNTRIES C,CITIES CT,
TOWNS T, DISTRICTS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND
CT.ID=A.CITYID AND D.ID=A.DISTRITID

GROUP BY U.NAMESURNAME 
