CREATE TABLE USERS(
ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
TELNR1 VARCHAR(15),
CREATEDATE DATETIME,
TELNR2 VARCHAR(15),
CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED (ID ASC))

CREATE TABLE ITEMS(
ID INT IDENTITY(1,1),
ITEMCODE  VARCHAR(50),
ITEMNAME VARCHAR(100),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE PAYMENDS(
ID INT IDENTITY(1,1),
ORDERID INT  ,
PAYMENTTYPE TINYINT,
DATE_ DATETIME,
ISOK BIT,
APPROVECODE VARCHAR(100),
PAYMENTOTAL FLOAT,
CONSTRAINT PK_PAYMENDS PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE ORDERSDETALIES(
ID INT IDENTITY(1,1),
ORDERID INT,
ITEMID INT,
AMOUNT INT ,
UNITPRICE FLOAT,
LINETOTAL FLOAT
CONSTRAINT PK_ODERSDETAILS PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE ORDERS(
ID INT IDENTITY(1,1),
USERID INT  ,
DATE_ DATETIME,
TOTALPRICE FLOAT,
STATUS TINYINT,
ADRESSID INT,
CONSTRAINT PK_ODERS PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE ADRESS(
ID INT IDENTITY(1,1),
USERID  INT,
COUNTRYID TINYINT,
CITYID SMALLINT,
TOWNID SMALLINT,
DISTRITID SMALLINT,
POSTAKCODE VARCHAR(15),
ADRESSTEXT  VARCHAR(100)
CONSTRAINT PK_ADRESS PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE COUNTRIES(
ID TINYINT IDENTITY(1,1),
COUNTRY VARCHAR(50)
CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE INVOICE(
ID INT IDENTITY(1,1),
ADRESSID INT  ,
ORDERID INT,
TOTALPRICE FLOAT,
DATE_ DATETIME,
CONSTRAINT PK_INVOICE PRIMARY KEY CLUSTERED (ID ASC))


CREATE TABLE INVOICEDETAILS(	
ID INT IDENTITY(1,1),	
INVOICEID INT  ,	
ODERDETAILID INT,	
ITEMID INT,	
AMOUNT INT,	
UNITPRICE FLOAT,	
LINETOTAL FLOAT	
CONSTRAINT PK_INVOICEDETAILS PRIMARY KEY CLUSTERED (ID ASC))	


CREATE TABLE DISTRICT(	
ID SMALLINT IDENTITY(1,1),	
TOWNID SMALLINT	
CONSTRAINT PK_DISTRICT PRIMARY KEY CLUSTERED (ID ASC))	


CREATE TABLE TOWNS(	
ID SMALLINT IDENTITY(1,1),	
TOWN VARCHAR(50)	
CONSTRAINT PK_TOWNS PRIMARY KEY CLUSTERED (ID ASC))	


CREATE TABLE CITIES(
ID SMALLINT IDENTITY(1,1),
CITY VARCHAR(50),
COUNTRYID TINYINT,
CONSTRAINT PK_CITIES PRIMARY KEY CLUSTERED (ID ASC))
