 --ürünlerin fiyat analizi, EN ÇOK HANGÝ AY SATILDI
SET STATISTICS IO ON
 SELECT ITM.ITEMCODE AS URUNKODU,
 ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS  WHERE ITEMID=ITM.ID) AS ENDUSUKFIYAT,
(SELECT MAX (UNITPRICE) FROM ORDERDETAILS  WHERE ITEMID=ITM.ID) AS ENYUKSEKFIYAT,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS  WHERE ITEMID=ITM.ID) AS ORTALAMAFIYAT,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS  WHERE ITEMID=ITM.ID) AS TOPLAMADET,
(
SELECT TOP 1 DATEPART (MONTH,O.DATE_) AS AY FROM ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID=O.ID 
WHERE OD.ITEMID=ITM.ID
GROUP BY DATEPART (MONTH,O.DATE_)
ORDER BY SUM(AMOUNT) DESC 
) AS ENCOKSATILANAY
 FROM 

 ITEMS ITM
 WHERE ITM.ID NOT IN --ITM ID DE OLMAYANLARI ÝSTÝYOR.
 (SELECT ITEMID FROM ORDERDETAILS) --BU ÝKÝSÝ AYNI ÞEYE ÇIAKR. ÝKÝSÝDE AYNI SONUCU VERÝR.
 -- DEMEK KÝ ÜRÜN VAR AMA SÝPARÝÞ VERÝLMEMÝÞ OLANLARI ÝSTÝYOR.
 --(SELECT MIN(UNITPRICE) FROM ORDERDETAILS  WHERE ITEMID=ITM.ID) IS NULL --BOÞ OLAN DEÐERLERÝ ÝSTEDÝK.
 ORDER BY ITM.ITEMNAME